In [5]:
%load_ext tensorboard
import tensorflow as tf
import numpy as np
from datetime import datetime
from tensorflow import keras
from tensorflow.estimator import LinearRegressor
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error, r2_score
print(tf.__version__)

The tensorboard extension is already loaded. To reload it, use:
  %reload_ext tensorboard
2.0.0


In [7]:
# Creating data
X_train = (np.random.sample((10000,5)))
y_train =  (np.random.sample((10000,1)))
X_train.shape
print(X_train)

[[0.57883652 0.46752051 0.90504023 0.08350397 0.84590723]
 [0.4736547  0.25998002 0.19713441 0.32023748 0.07991817]
 [0.31000902 0.34301832 0.99481573 0.17542678 0.41232082]
 ...
 [0.52525513 0.87377231 0.49792188 0.27840154 0.70937784]
 [0.50730343 0.49295665 0.80378642 0.10652229 0.97125527]
 [0.66183562 0.63710159 0.64195817 0.54792858 0.55735742]]


In [8]:
# Build the tf.keras.Sequential model by stacking layers.
model = tf.keras.models.Sequential([
  #tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(256, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(256, activation='relu'),
  tf.keras.layers.Dense(10, activation='softmax')
])
model.compile(optimizer='adam',
              loss='sparse_categorical_crossentropy',
              metrics=['accuracy'])
logdir="logs/fit/" + datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = keras.callbacks.TensorBoard(log_dir=logdir)

In [9]:
# Train the estimator
model.fit(X_train, y_train, epochs=10, callbacks=[tensorboard_callback])

Train on 10000 samples
Epoch 1/10
10000/10000 [==============================] - 2s 153us/sample - loss: 0.0703 - accuracy: 0.0000e+00
Epoch 2/10
10000/10000 [==============================] - 1s 66us/sample - loss: 6.5875e-06 - accuracy: 0.0000e+00
Epoch 3/10
10000/10000 [==============================] - 1s 67us/sample - loss: 1.6476e-06 - accuracy: 0.0000e+00
Epoch 4/10
10000/10000 [==============================] - 1s 66us/sample - loss: 9.5847e-07 - accuracy: 0.0000e+00
Epoch 5/10
10000/10000 [==============================] - 1s 66us/sample - loss: 1.1063e-06 - accuracy: 0.0000e+00
Epoch 6/10
10000/10000 [==============================] - 1s 66us/sample - loss: 5.1265e-07 - accuracy: 0.0000e+00
Epoch 7/10
10000/10000 [==============================] - 1s 70us/sample - loss: 2.5334e-07 - accuracy: 0.0000e+00
Epoch 8/10
10000/10000 [==============================] - 1s 78us/sample - loss: 1.4469e-07 - accuracy: 0.0000e+00
Epoch 9/10
10000/10000 [==============================] - 1s

In [10]:
model.evaluate(X_train, y_train)

10000/1 [===============================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================================

[1.9371335691431568e-08, 0.0]

In [11]:
%tensorboard --logdir logs

Reusing TensorBoard on port 6007 (pid 13950), started 0:08:38 ago. (Use '!kill 13950' to kill it.)

## The original example

In [12]:
# Transforming the data and creating a model

feature_columns = [
      tf.feature_column.numeric_column('x', shape=X_train.shape[1:])]
opt = tf.optimizers.Adam
DNN_reg = tf.estimator.DNNRegressor(
    hidden_units=[500, 300], feature_columns=feature_columns, model_dir='train/linreg', optimizer=opt)

INFO:tensorflow:Using default config.
INFO:tensorflow:Using config: {'_model_dir': 'train/linreg', '_tf_random_seed': None, '_save_summary_steps': 100, '_save_checkpoints_steps': None, '_save_checkpoints_secs': 600, '_session_config': allow_soft_placement: true
graph_options {
  rewrite_options {
    meta_optimizer_iterations: ONE
  }
}
, '_keep_checkpoint_max': 5, '_keep_checkpoint_every_n_hours': 10000, '_log_step_count_steps': 100, '_train_distribute': None, '_device_fn': None, '_protocol': None, '_eval_distribute': None, '_experimental_distribute': None, '_experimental_max_worker_delay_secs': None, '_session_creation_timeout_secs': 7200, '_service': None, '_cluster_spec': <tensorflow.python.training.server_lib.ClusterSpec object at 0x7feccc744630>, '_task_type': 'worker', '_task_id': 0, '_global_id_in_cluster': 0, '_master': '', '_evaluation_master': '', '_is_chief': True, '_num_ps_replicas': 0, '_num_worker_replicas': 1}
